### PR TITLE
:sparkles: add installation script

### PR DESCRIPTION
**Pull request by rediculum**
- Added an installation script
- Replaced systemd files by a template
- TODO: update README

### CODE REVIEW

**Comment by rediculum** [comment]
resolved #17

**Comment by freakydude** [comment]
Hi.

Scrolling through the code looks good so far. 
I will let it open, until i got a chance to test it. Maybe there are others that could try out this too.

Feedback is welcome.

**Comment by freakydude** [comment]
Tested It on my CB1 with custom user name: It worked, but I have some minor points:

- Please do not remove the "original" service file from the repository. There is no readme.md adaption with this pull request yet and my old blog article is still not adapted.
- Install.sh
  - "Please specify your serial port name" --> which one should I type in? The one, where the touchscreen is connected to, not the PI or CB1
  - The section to the moonraker.conf is added without an empty first line, I would like to see one there ;-) 
    ```
    [update_manager mobileraker]
    type: git_repo
    path: ~/mobileraker_companion
    origin: https://github.com/Clon1998/mobileraker_companion.git
    primary_branch: main
    managed_services: mobileraker
    env: ~/mobileraker-env/bin/python
    requirements: scripts/mobileraker-requirements.txt
    install_script: scripts/install-mobileraker-companion.sh
    
    [update_manager timelapse]
    type: git_repo
    primary_branch: main
    path: ~/moonraker-timelapse
    origin: https://github.com/mainsail-crew/moonraker-timelapse.git
    managed_services: klipper moonraker
    [update_manager klipper-serial-btt]
    type: git_repo
    primary_branch: main
    path: ~/klipper-serial-btt
    origin: https://github.com/freakydude/klipper-serial-btt.git
    managed_services: klipper
    ```

Thank you for your work
freakyDude

**Comment by rediculum** [comment]
> Tested It on my CB1 with custom user name: It worked, but I have some minor points:
> 
> * Please do not remove the "original" service file from the repository. There is no readme.md adaption with this pull request yet and my old blog article is still not adapted.
> * Install.sh
>   
>   * "Please specify your serial port name" --> which one should I type in? The one, where the touchscreen is connected to, not the PI or CB1
>   * The section to the moonraker.conf is added without an empty first line, I would like to see one there ;-)
>     ```
>     [update_manager mobileraker]
>     type: git_repo
>     path: ~/mobileraker_companion
>     origin: https://github.com/Clon1998/mobileraker_companion.git
>     primary_branch: main
>     managed_services: mobileraker
>     env: ~/mobileraker-env/bin/python
>     requirements: scripts/mobileraker-requirements.txt
>     install_script: scripts/install-mobileraker-companion.sh
>     
>     [update_manager timelapse]
>     type: git_repo
>     primary_branch: main
>     path: ~/moonraker-timelapse
>     origin: https://github.com/mainsail-crew/moonraker-timelapse.git
>     managed_services: klipper moonraker
>     [update_manager klipper-serial-btt]
>     type: git_repo
>     primary_branch: main
>     path: ~/klipper-serial-btt
>     origin: https://github.com/freakydude/klipper-serial-btt.git
>     managed_services: klipper
>     ```
> 
> Thank you for your work freakyDude

Done in 62a6727c16fbb074cde5bc58ebfaf47f929c3d65

**Pull request merged**
